#!/bin/bash

ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/"

print_usage() {
cat<<EOF
                 __       _           _   
  /\/\  _ __    /__\ ___ | |__   ___ | |_ 
 /    \| '__|  / \/// _ \| '_ \ / _ \| __|
/ /\/\ | |_   / _  | (_) | |_) | (_) | |_ 
\/    \|_(_)  \/ \_/\___/|_.__/ \___/ \__|
                _       _        __ _ _      
               | |     | |      / _(_) |     
 __      ____ _| |_ ___| |__   | |_ _| | ___ 
 \ \ /\ / / _' | __/ __| '_ \  |  _| | |/ _ \\
  \ V  V / (_| | || (__| | | | | | | | |  __/
   \_/\_/ \__'_|\__\___|_| |_| |_| |_|_|\___|
																			                                            
Mr. Robot Watch file script.

This script watches a file.

Usage: 
    ./watch_files <ip_address> <dir_path>
    ./watch_files 192.168.0.117 /home/my_user/camera

EOF
}

watch_file() {
    if [[ ${#@} < 2 ]]
    then
		print_usage
		exit 1
    fi

	# Use --foreground to run the script in foreground
	inoticoming --logfile watch_log --pid-file watch_pid $2 $ABSOLUTE_PATH/send_file $1 $2/{} \;
	if [[ $? -ne 0 ]]
	then
		echo Failed to watch files
	fi
}


watch_file $1 $2
